# Approximates CSS box-shadow (offset-y, blur, colour) with stacked translucent layers (Gaussian-ish fall-off).
# Output: res/drawable/shadow_<name>.xml (layer-list) + colour resources appended to res/values/colors.xml
$res = Join-Path $PSScriptRoot "..\app\src\main\res"
$inv = [Globalization.CultureInfo]::InvariantCulture
$enc = New-Object Text.UTF8Encoding $false
function Dim([double]$v) {
  $v = [Math]::Round($v * 2) / 2
  $neg = $v -lt 0; $a = [Math]::Abs($v)
  $s = $a.ToString("0.#", $inv).Replace(".", "_")
  if ($neg) { return "@dimen/_minus${s}sdp" } else { return "@dimen/_${s}sdp" }
}
function Shadow($name, [string]$rgb, [double]$alpha, [double]$oy, [double]$blur, [string]$shape, [double]$radius, [int]$n) {
  $each = 1 - [Math]::Pow(1 - $alpha, 1.0 / $n)
  $a = [int][Math]::Round($each * 255)
  $colorName = "color_shadow_$name"
  $sb = New-Object Text.StringBuilder
  [void]$sb.AppendLine('<?xml version="1.0" encoding="utf-8"?>')
  [void]$sb.AppendLine("<!-- CSS box-shadow: 0 ${oy}px ${blur}px rgba($rgb, $alpha) approximated with $n stacked layers. Generated by tools/gen_shadows.ps1 -->")
  [void]$sb.AppendLine('<layer-list xmlns:android="http://schemas.android.com/apk/res/android">')
  for ($j = 0; $j -lt $n; $j++) {
    $d = -$blur / 2 + ($j + 0.5) * $blur / $n
    $l = Dim (-$d); $t = Dim ($oy - $d); $b = Dim (-$oy - $d)
    [void]$sb.AppendLine("    <item android:left=""$l"" android:top=""$t"" android:right=""$l"" android:bottom=""$b"">")
    if ($shape -eq "oval") {
      [void]$sb.AppendLine('        <shape android:shape="oval"><solid android:color="@color/' + $colorName + '" /></shape>')
    } else {
      $r = [Math]::Max($radius + $d, 0)
      [void]$sb.AppendLine('        <shape android:shape="rectangle"><solid android:color="@color/' + $colorName + '" /><corners android:radius="' + (Dim $r) + '" /></shape>')
    }
    [void]$sb.AppendLine('    </item>')
  }
  [void]$sb.AppendLine('</layer-list>')
  [IO.File]::WriteAllText("$res\drawable\shadow_$name.xml", $sb.ToString(), $enc)
  $hex = ("#{0:X2}{1}" -f $a, $rgb)
  return "    <color name=""$colorName"">$hex</color>"
}
$colors = @()
$colors += Shadow "nav"      "000000" 0.5  12 32 "rect" 26 8
$colors += Shadow "fab"      "6246FF" 0.3   8 20 "oval" 0  6
$colors += Shadow "tile"     "000000" 0.35  4 12 "rect" 12 4
$colors += Shadow "art_a"    "000000" 0.4  12 28 "rect" 16 6
$colors += Shadow "art_b"    "000000" 0.5  18 40 "rect" 20 7
$colors += Shadow "art_c"    "000000" 0.45 18 40 "rect" 20 7
$cp = "$res\values\colors.xml"
$txt = [IO.File]::ReadAllText($cp)
$txt = [regex]::Replace($txt, '\s*<color name="color_shadow_[^"]+">[^<]*</color>', '')
$txt = $txt -replace '</resources>', (($colors -join "`r`n") + "`r`n</resources>")
[IO.File]::WriteAllText($cp, $txt, $enc)
"shadows done"
